Added 7th module tasks
js-tasks-ru/jsbasic-20230911_creed-jke pull request #8
Opened 2023-10-18 12:25 UTC by cReedJke

С 7-4 я намучился, конечно
Не знаю, что так застрял, сначала все в куче было, потом по методам разбрасал все, какие-то моменты вопросы вызывали, но вроде как разобрался
В 3 со своей реализацией(отличающейся 1 строкой, по идее, от подсказки, разве что код "грубее") все работало, а вот в 4 сначала сам реализовать пытался способ перетаскивания ползунка, что-то не так все было, потом подсматривал реализацию и к 7-3, и к 7-4, чтобы сделать как надо, потом оставил что-то между своей реализацией и подсказочной
Хотелось бы, чтобы pointerup срабатывал на body хотя бы, но реализовать не удалось, и из-за отставания от ДЗ и того, сколько уже времени потратил на задачу, бросил эту идею. Ведь требование - чтобы pointerup на слайдере срабатывал, это есть
И хотелось код из обработчика клика вынести в отдельный метод, чтобы потом этот метод и с pointerdown использовать(т.к код и в клике, и в pointerdown один и то же по итогу), но не придумал, как прикрутить customEvent, чтобы он тоже был отдельным методом, чтобы для клика его добавить, а для pointerup не добавлять, и по итогу копипаста в двух обработчиках событий
Не очень доволен тем, как выполнил, не хватает, конечно, реальной практики с таким, чтобы и по структуре кода как-то больше понимания иметь, куда что выносить, ну и понимания иногда. Ну практика, практика, все понятно

2023-10-18 12:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-18 18:08 UTC, SinimaWath requested changes

2023-10-18 18:08 UTC, SinimaWath commented on 7-module/4-task/index.js
> +    this.elem.addEventListener('pointerup', this.#onPointerUp);
а почему бы здесь просто не заменить на: `document.addEventListener('pointerup', this.#onPointerUp)` ? Судя по коду все должно работать

2023-10-18 18:08 UTC, SinimaWath commented on 7-module/4-task/index.js
> +    progress.style.width = 100 / (this.steps - 1) * stepValue + '%';
Как будто, это выносится в метод очень просто:
```

#onElementClick = (event) => {
    const sliderValue = this.elem.querySelector('.slider__value');
    const currentActive = this.elem.querySelector('.slider__step-active');
    const thumb = this.elem.querySelector('.slider__thumb');
    const progress = this.elem.querySelector('.slider__progress');

    let innerClick = event.clientX - this.elem.offsetLeft;
    const stepWidth = this.elem.clientWidth / (this.steps - 1);
    let stepValue = Math.round(innerClick / stepWidth);

    sliderValue.textContent = stepValue;
    currentActive.classList.remove('slider__step-active');
    for (let span of this.elem.querySelectorAll('span')) {
      if (span.dataset.step == stepValue) span.classList.add('slider__step-active');
    }
    thumb.style.left = 100 / (this.steps - 1) * stepValue + '%';
    progress.style.width = 100 / (this.steps - 1) * stepValue + '%';
}


#onClick = (event) => {
   this.#onElementClick(event);
   
    this.elem.dispatchEvent(new CustomEvent('slider-change', {
      detail: Number(this.elem.querySelector('.slider__value').textContent),
      bubbles: true
    })); 
}

#onPointerDown = (event) => {
   this.#onElementClick(event);
   
    document.addEventListener('pointermove', this.#onPointerMove);
    this.elem.addEventListener('pointerup', this.#onPointerUp);
} 


```

2023-10-19 20:25 UTC, SinimaWath approved these changes
Все круто

2023-10-19 20:26 UTC, merged